# Generated by Django 4.1.7 on 2023-03-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_audition'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
