# Generated by Django 4.1.7 on 2023-03-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_category_options_alter_people_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
