# Generated by Django 4.1.7 on 2023-04-26 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0003_audition_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['id'], 'verbose_name': 'Stars', 'verbose_name_plural': 'Stars'},
        ),
        migrations.AddField(
            model_name='people',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
